<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <title>Interface Admin</title>
  </head>
	</head>
	<body>
    <header>
      <nav>
        <ul id="navigation">
          <li><a href="../../src/index.php">retour vers le blog</a></li>
        </ul>
      </nav>
    </header>
    <main>
			<table>
	      <tr>
	        <td><a href="../src/insert.php">Créer un Nouvel Article</a></td>
				</tr>
				<tr>
					<td><a href="../src/edit.php">Editer/Modifier les articles</a></td>
				</tr>
			<table>
    </main>
	</body>
</html>
