<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>

		<!-- Responsive -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

		<!-- Fontewasome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<!-- Normalize -->
		<link rel="stylesheet" type="text/css" href="../css/normalize.css"/>

		<!-- Style -->
		<link rel="stylesheet" type="text/css" href="../css/style.css"/>

		<title>Portfolio</title>
	</head>
	<header class="maxSize">
		<nav>
			<h1><a href="#"><img src="../img/logo.svg"><p>John&nbsp;Doe</p></a></h1>
			<ul id="navigation">
  			<li><a href="#" class="nav-1"><i class="fas fa-home"></i>Accueil</a></li>
 				<li><a href="../admin/src/index.php"><i class="fas fa-user-circle"></i>Admin</a></li>
  			<div class="clear"></div>
			</ul>
		</nav>
		<div class="clear"></div>
	</header>
	<body>
		<!-- Pages : <main>... -->
		<?php include $template ?>
	<footer>
		<a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" style="border-width:0" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png" /></a><br /><span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants, Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br />Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="http://www.justine-muller.fr">Justine Muller</a>.
	</footer>
	</body>
</html>
