<main>
  <!-- Fonction php -->
  <?php foreach($SelectedOneArticle as $article) : ?>
    <article class="article container textCenter">
      <h2><?= $article['articleTitle'] ?></h2>
      <p>Rédigé par : <?= $article['pseudo'] ?>, le <?php $date = date_create($article['createDate']); echo date_format($date, 'd/m/Y');?></p>
      <img src="../img/recette/<?= $article['articleImage'] ?>" alt="<?= $article['articleTitle'] ?>">
      <p><?= nl2br($article['articleContent']) ?></p>
    </article>
  <?php endforeach ?>
</main>
